name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./tests

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm install
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Run npm test
        run: npm run gh-actions-test
        working-directory: ${{env.working-directory}}
